### ISSUE TITLE
Badge doesnt refresh.

### ISSUE THREAD

**Issue by mbassus** [mediabounds/streamdeck-jira#5]
Have Streamdeck XL with 22 JQLs. Dont know, if its a API problem or not. When i go into the jql, add a space, then its refreshing.

Also, i added with a macro (2 inputvariables and a PHP Backendscript) a "Create new issue" function. Maybe you can add this into the plugin :) ? Maybe i can help!
![grafik](https://user-images.githubusercontent.com/76403680/216847687-b97f7940-042b-425f-a000-cc510efd13af.png)

**Comment by mediabounds** [comment]
Wow! 22 is definitely more than I tested with at once--but I only have a mini. I wouldn't think that 22 would be crossing any sort of limit. 

The _intended_ behavior is that as long as the action is visible, it should update the badge every 2 minutes (but if you switch profiles/pages or the device goes to sleep, it pauses updating). It will also immediately update the badge if you change any setting in the property inspector.

Can you try two things for me?
1. Can you try restarting the Stream Deck software? If the actions didn't know they were visible, then they might not update automatically. Restarting the software might help.

2. If restarting Stream Deck doesn't help, then we need to look at Stream Deck's logs. The plugin will log error messages to the Stream Deck log. Logs are saved to disk per plugin in the folder `~/Library/Logs/StreamDeck/` on macOS and `%appdata%\Elgato\StreamDeck\logs\` on Windows.

You're welcome to post the full log files here--but you might want to search through it first to see if any other plugins logged information you don't want to post.

(And I welcome any contributions back to the plugin! I had considered adding an action for adding an issue, but I ended up using the open URL action for that.)

**Comment by mediabounds** [comment]
Closing since I haven’t heard back—but feel free to reopen if the issue is still occurring!
