### ISSUE TITLE
Are there any plans to create streamdeck-atlassian with more application support?

### ISSUE THREAD

**Issue by khashashin** [mediabounds/streamdeck-jira#7]
Great plugin, thank you very much!

I am especially interested in Bitbucket. New plugin with ability to track status of pipelines or amount of merge requests would be very nice.

**Comment by mediabounds** [comment]
Sorry for the delay--I don't have any plans currently, unfortunately! I don't use Bitbucket in my organization so I don't have any repos or pipelines to test with. But I'm not against adding it to this plugin and would welcome any contributions!
